- hosts: all
  tasks:
        - name: Making directory for packages...
          file:
                  name: /pkgs
                  state: directory

        - name: Copying hadoop rpm file...
          copy:
                src: /root/hadoop-1.2.1-1.x86_64.rpm
                dest: /pkgs/

        - name: Copying jdk rpm...
          copy:
                  src: /root/jdk-8u171-linux-x64.rpm
                  dest: /pkgs/

        - name: Installing jdk...
          yum:
                  name: /pkgs/jdk-8u171-linux-x64.rpm
                  state: installed

        - name: Installing hadoop...
          command: "rpm -i /pkgs/hadoop-1.2.1-1.x86_64.rpm --force"


- hosts: namenode
  tasks:
          - include_vars: vars.yml

          - name: Copying config file core-site.xml to master
            copy:
                    src: /playbooks/core-site_master.xml
                    dest: /etc/hadoop/core-site.xml

          - name: Copying file hdfs-site.xml to master
            template:
                    src: /playbooks/hdfs-site_master.j2
                    dest: /etc/hadoop/hdfs-site.xml
                    mode: u=rw

          - name: Creating namenode directory
            file:
                    path: "{{ nn_dir }}"
                    state: directory

          - name: Formatting namenode directory
            shell: "hadoop namenode -format -force -nonInteractive"
            #ignore_errors: yes

          - name: Starting namenode...
            command: "hadoop-daemon.sh start namenode"


- hosts: datanodes
  tasks:
          - include_vars: vars.yml

          - name: Copying config file core-site.xml to dn
            template:
                    src: /playbooks/core-site_slave.j2
                    dest: /etc/hadoop/core-site.xml

          - name: Copying file hdfs-site.xml to dn
            template:
                    src: /playbooks/hdfs-site_slave.j2
                    dest: /etc/hadoop/hdfs-site.xml
                    mode: u=rw

          - name: Creating datanode directory
            file:
                    path: "{{ dn_dir }}"
                    state: directory

          - name: Starting namenode...
            command: " hadoop-daemon.sh start datanode"

